# application name 설정
spring:
  application:
    name: bowmeow-product

# port
server:
  port: 8083

# gRpc 설정
grpc:
  server:
    host: localhost
    port: 9092  # gRPC ?? ??

# database 연결 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 스키마 자동 생성 전략 (create, update, validate, none 중 선택)
    show-sql: true  # 쿼리 로그를 콘솔에 출력
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 사용 시 적절한 방언 설정
